modLoader="javafml"
loaderVersion="[36,)"
license="Check Curseforge for details"

[[mods]]
	modId="tactical_fishing"
	version="1.1"
	displayName="Tactical Fishing"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/tactical-fishing/"
	logoFile="modicon.png"
	credits="PedroRalof"
	authors="Fuffles_"
	description='''Makes it possible to make Buckets of Fish while fishing with Water Buckets.'''

[[dependencies.tactical_fishing]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"